using Test
using Soliton
using FFTW

@testset "New Analysis Utilities" begin
    @testset "pulse_energy_estimate / peak_power_estimate (analytic shape factors)" begin
        Pmax = 5000.0  # W
        FWHM = 50e-15  # s

        for shape in (:sech, :gaussian, :lorentzian)
            E = pulse_energy_estimate(Pmax, FWHM; shape=shape)
            @test E > 0
            @test peak_power_estimate(E, FWHM; shape=shape) ≈ Pmax rtol=1e-10
        end

        # Cross-check against the numerically-integrated energy of actual Pulse objects
        # generated by sech_pulse/gaussian_pulse/lorentzian_pulse: the analytic estimate
        # should match pulse_energy() on a grid wide/fine enough to capture the tails.
        grid = create_grid(2^16, 50 * FWHM, 1550e-9)

        p_sech = sech_pulse(grid, Pmax, FWHM)
        @test pulse_energy_estimate(Pmax, FWHM; shape=:sech) ≈ pulse_energy(p_sech) rtol=1e-3

        p_gauss = gaussian_pulse(grid, Pmax, FWHM)
        @test pulse_energy_estimate(Pmax, FWHM; shape=:gaussian) ≈ pulse_energy(p_gauss) rtol=1e-3

        p_lorentz = lorentzian_pulse(grid, Pmax, FWHM)
        @test pulse_energy_estimate(Pmax, FWHM; shape=:lorentzian) ≈
            pulse_energy(p_lorentz) rtol=1e-2

        # Known numeric constants (regression guard on the closed-form factors)
        @test pulse_energy_estimate(1.0, 1.0; shape=:sech) ≈ 1.134592657106511 rtol=1e-12
        @test pulse_energy_estimate(1.0, 1.0; shape=:gaussian) ≈ 1.0644670194312262 rtol=1e-12
        @test pulse_energy_estimate(1.0, 1.0; shape=:lorentzian) ≈ 1.2203312255379457 rtol=1e-12

        @test_throws ArgumentError pulse_energy_estimate(-1.0, 1.0)
        @test_throws ArgumentError pulse_energy_estimate(1.0, -1.0)
        @test_throws ArgumentError pulse_energy_estimate(1.0, 1.0; shape=:triangular)
        @test_throws ArgumentError peak_power_estimate(1.0, 1.0; shape=:triangular)
    end

    @testset "average_power / pulse_energy_from_average / peak_power_from_average" begin
        E = 1.25e-9  # J
        f_rep = 80e6 # Hz
        Pavg = average_power(E, f_rep)
        @test Pavg ≈ E * f_rep
        @test pulse_energy_from_average(Pavg, f_rep) ≈ E rtol=1e-12

        FWHM = 100e-15
        Pmax_expected = peak_power_estimate(E, FWHM; shape=:sech)
        @test peak_power_from_average(Pavg, f_rep, FWHM; shape=:sech) ≈ Pmax_expected rtol=1e-12

        # Sanity: 100 mW average, 80 MHz, 100 fs sech pulses -> peak power of order kW
        Ppeak = peak_power_from_average(0.1, 80e6, 100e-15; shape=:sech)
        @test 1e3 < Ppeak < 2e4

        @test_throws ArgumentError average_power(-1.0, 1e6)
        @test_throws ArgumentError average_power(1.0, 0.0)
        @test_throws ArgumentError pulse_energy_from_average(1.0, -1.0)
    end

    @testset "soliton_period" begin
        beta2 = -20e-27
        T0 = 100e-15
        @test soliton_period(beta2, T0) ≈ (π / 2) * dispersion_length(beta2, T0)
        @test soliton_period(beta2, T0) > 0
        # Scales quadratically with T0 for fixed beta2
        @test soliton_period(beta2, 2 * T0) ≈ 4 * soliton_period(beta2, T0)
    end

    @testset "Modulation instability gain" begin
        beta2 = -20e-27  # anomalous
        gamma = 1.3e-3   # 1/(W*m)
        P0 = 1.0         # W

        Omega_max = mi_peak_frequency(beta2, gamma, P0)
        g_max = modulation_instability_gain(beta2, gamma, P0, Omega_max)
        @test g_max ≈ 2 * gamma * P0 rtol=1e-10

        # g(Omega) is symmetric and vanishes at and beyond the MI edge
        Omega_c = mi_bandwidth(beta2, gamma, P0) / 2
        @test modulation_instability_gain(beta2, gamma, P0, Omega_c) ≈ 0.0 atol=1e-9
        @test modulation_instability_gain(beta2, gamma, P0, 1.01 * Omega_c) == 0.0
        @test modulation_instability_gain(beta2, gamma, P0, -Omega_max) ≈ g_max rtol=1e-10

        # Numerically confirm Omega_max is indeed where the gain peaks
        Omegas = range(0.0, Omega_c; length=2001)
        gains = modulation_instability_gain(beta2, gamma, P0, collect(Omegas))
        @test length(gains) == length(Omegas)
        idx = argmax(gains)
        @test isapprox(Omegas[idx], Omega_max; rtol=1e-2)

        # No MI in normal dispersion
        @test modulation_instability_gain(20e-27, gamma, P0, 1e12) == 0.0
        @test_throws ArgumentError mi_peak_frequency(20e-27, gamma, P0)
        @test_throws ArgumentError mi_bandwidth(20e-27, gamma, P0)
    end

    @testset "instantaneous_frequency (chirp)" begin
        # A chirped Gaussian A(t) = exp(-t^2/2tau^2) * exp(i*b*t^2) has an exact
        # instantaneous-frequency deviation delta_omega(t) = -2*b*t.
        N = 2^13
        tau = 100e-15
        b = 5e27 # rad/s^2
        time_window = 40 * tau
        grid = create_grid(N, time_window, 1550e-9)

        At = @. exp(-grid.t^2 / (2 * tau^2)) * cis(b * grid.t^2)
        AW = ifft(At)
        pulse = Pulse(At, AW, grid)

        domega = instantaneous_frequency(pulse)
        @test length(domega) == N

        theory = @. -2 * b * grid.t
        # Compare only where intensity is a meaningful fraction of the peak
        # (phase is numerically ill-defined in the low-intensity wings).
        intensity = abs2.(At)
        mask = intensity .> 0.05 * maximum(intensity)
        @test isapprox(domega[mask], theory[mask]; rtol=1e-3)

        # An unchirped pulse has (near) zero instantaneous frequency deviation
        # across its high-intensity core.
        p_flat = gaussian_pulse(grid, 1.0, tau)
        domega_flat = instantaneous_frequency(p_flat)
        intensity_flat = abs2.(p_flat.At)
        mask_flat = intensity_flat .> 0.1 * maximum(intensity_flat)
        @test all(x -> isapprox(x, 0.0; atol=1e-6), domega_flat[mask_flat])
    end
end
